/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int VAR = 6;
  /** RegularExpression Id. */
  int ACHAVES = 7;
  /** RegularExpression Id. */
  int FCHAVES = 8;
  /** RegularExpression Id. */
  int APARENTESES = 9;
  /** RegularExpression Id. */
  int FPARENTESES = 10;
  /** RegularExpression Id. */
  int VIRGULA = 11;
  /** RegularExpression Id. */
  int PVIRGULA = 12;
  /** RegularExpression Id. */
  int INT = 13;
  /** RegularExpression Id. */
  int BOOL = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int DO = 18;
  /** RegularExpression Id. */
  int RETURN = 19;
  /** RegularExpression Id. */
  int PRINT = 20;
  /** RegularExpression Id. */
  int ATRIB = 21;
  /** RegularExpression Id. */
  int FUNCTION = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int OP = 25;
  /** RegularExpression Id. */
  int ID = 26;
  /** RegularExpression Id. */
  int NUMERO = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"var\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\"int\"",
    "\"bool\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"print\"",
    "\":=\"",
    "\"function\"",
    "\"true\"",
    "\"false>\"",
    "<OP>",
    "<ID>",
    "<NUMERO>",
  };

}
